services:
  flask_api:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key-here
      - DATABASE_URL=sqlite:///users.db
    volumes:
      - ..:/app
    command: python server.py