
services:
  flask_api:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=your-secret-key-here
      - DB_HOST=db
      - DB_NAME=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    volumes:
      - ..:/app
    command: python server.py
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    ports:
      - "5432:5432"  # This line exposes the PostgreSQL port
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: